In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = sns.load_dataset("iris")
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [3]:
#X is feature vectors
X = df[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]

# y is labels
Y = df[['species']]

In [4]:
from sklearn.preprocessing import StandardScaler

X_scaled = StandardScaler().fit_transform(X)

In [5]:
features =X.T  # X 데이터는 150 × 4 이라면,
               # feature 는 4 × 150 이다.

covariance_matrix = np.cov(features)
print(covariance_matrix)

[[ 0.68569351 -0.042434    1.27431544  0.51627069]
 [-0.042434    0.18997942 -0.32965638 -0.12163937]
 [ 1.27431544 -0.32965638  3.11627785  1.2956094 ]
 [ 0.51627069 -0.12163937  1.2956094   0.58100626]]


In [7]:

values, vectors = np.linalg.eig(covariance_matrix)

print('\nEigenvalues \n%s '% values[:])
print('\nEigenvectros \n%s'  %  vectors[:])


Eigenvalues 
[4.22824171 0.24267075 0.0782095  0.02383509] 

Eigenvectros 
[[ 0.36138659 -0.65658877 -0.58202985  0.31548719]
 [-0.08452251 -0.73016143  0.59791083 -0.3197231 ]
 [ 0.85667061  0.17337266  0.07623608 -0.47983899]
 [ 0.3582892   0.07548102  0.54583143  0.75365743]]


In [8]:
4.22824171 / (4.22824171+0.24267075+0.0782095+0.02383509)

0.9246187234581614

In [9]:
0.24267075  / (4.22824171+0.24267075+0.0782095+0.02383509)

0.05306648353498093

In [10]:
0.9246187234581614 + 0.05306648353498093

0.9776852069931423

In [13]:
u1 = 4.22824171 * np.array([ 0.36138659, -0.65658877, -0.58202985,  0.31548719])

In [15]:
u1

array([ 1.52802985, -2.77621602, -2.46096289,  1.3339561 ])

In [18]:
np.dot(np.array([5.1,3.5,1.4,0.2]),u1)

-5.1023606554033

In [ ]:
1.52802985 * 5.1 + 3.5* -2.77621602 

In [19]:
u2 = 0.24267075 * np.array([ -0.08452251, -0.73016143 , 0.59791083 ,-0.3197231])

In [20]:
np.dot(np.array([5.1,3.5,1.4,0.2]),u2)

-0.537151526519328