In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = sns.load_dataset("iris")
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [3]:
#X is feature vectors
X = df[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]

# y is labels
Y = df[['species']]

In [4]:
from sklearn.preprocessing import StandardScaler

X_scaled = StandardScaler().fit_transform(X)

In [5]:
features =X_scaled.T  # X 데이터는 150 × 4 이라면,
               # feature 는 4 × 150 이다.

covariance_matrix = np.cov(features)
print(covariance_matrix)

[[ 1.00671141 -0.11835884  0.87760447  0.82343066]
 [-0.11835884  1.00671141 -0.43131554 -0.36858315]
 [ 0.87760447 -0.43131554  1.00671141  0.96932762]
 [ 0.82343066 -0.36858315  0.96932762  1.00671141]]


In [6]:

values, vectors = np.linalg.eig(covariance_matrix)

print('\nEigenvalues \n%s '% values[:])
print('\nEigenvectros \n%s'  %  vectors[:])


Eigenvalues 
[2.93808505 0.9201649  0.14774182 0.02085386] 

Eigenvectros 
[[ 0.52106591 -0.37741762 -0.71956635  0.26128628]
 [-0.26934744 -0.92329566  0.24438178 -0.12350962]
 [ 0.5804131  -0.02449161  0.14212637 -0.80144925]
 [ 0.56485654 -0.06694199  0.63427274  0.52359713]]


In [7]:
2.93808505  / (2.93808505+0.9201649+0.14774182+0.02085386)

0.7296244554574594

In [8]:
0.9201649  / (4.22824171+0.24267075+0.0782095+0.02383509)

0.20121879342820417

In [9]:
0.7296244554574594 + 0.20121879342820417

0.9308432488856635

In [10]:
u1 = 2.93808505 * np.array([  0.52106591, -0.37741762, -0.71956635, 0.26128628])

In [11]:
u1

array([ 1.53093596, -1.10888507, -2.11414714,  0.76768131])

In [15]:
u2 = 0.9201649 * np.array([  -0.26934744, -0.92329566 , 0.24438178 ,-0.12350962])

In [13]:
sepal_length_sepal_width_petal_length_petal_width_1 = np.dot(X_scaled,u1)

In [14]:
sepal_length_sepal_width_petal_length_petal_width_1

array([-6.85249833e-01,  2.20058450e-01, -5.41302880e-01, -7.11866740e-01,
       -1.12601184e+00, -1.30818102e+00, -1.25643776e+00, -7.35651010e-01,
       -4.52181044e-01, -2.56417558e-01, -7.59435279e-01, -1.22681419e+00,
       -6.64933684e-02, -6.33506569e-01, -4.22731498e-01, -1.78766369e+00,
       -8.27530289e-01, -5.84198265e-01, -5.97470084e-01, -1.47014622e+00,
       -2.33975376e-01, -1.11383289e+00, -1.38736211e+00, -2.32059665e-01,
       -1.58730224e+00,  1.65233333e-01, -6.53710557e-01, -6.19912266e-01,
       -2.44487826e-01, -9.01790930e-01, -4.61028924e-01,  2.08453127e-01,
       -2.25253437e+00, -1.73008113e+00, -1.55365990e-01,  1.35360553e-01,
        1.76913851e-01, -1.41256366e+00, -5.87280117e-01, -5.50150760e-01,
       -6.49535832e-01,  1.48610400e+00, -1.09780363e+00, -7.06869177e-01,
       -1.84974538e+00,  1.35609768e-01, -1.69136047e+00, -8.46965814e-01,
       -9.44935529e-01, -3.60226570e-01,  8.52290457e-01,  8.06658908e-02,
        7.82778165e-01,  

In [16]:
sepal_length_sepal_width_petal_length_petal_width_2 = np.dot(X_scaled,u2)

In [17]:
sepal_length_sepal_width_petal_length_petal_width_2

array([-0.79438116,  0.24353806, -0.10032469,  0.15083984, -0.95992197,
       -1.658336  , -0.46361582, -0.55599776,  0.58926329,  0.07570752,
       -1.26283535, -0.48315516,  0.28852869,  0.40033901, -2.00801631,
       -2.7518482 , -1.70946048, -0.80934106, -1.53789677, -1.38327458,
       -0.65055847, -1.20266293, -0.8909235 , -0.40977439, -0.4448118 ,
        0.23906956, -0.57313643, -0.81163078, -0.62884035, -0.06198133,
        0.10355948, -0.70604049, -1.97010018, -2.28350495,  0.06074763,
       -0.20319802, -0.92728523, -0.91493134,  0.38091062, -0.58602849,
       -0.79209144,  1.70492083, -0.01023248, -0.79862777, -1.34711   ,
        0.2586089 , -1.35553357, -0.05751283, -1.23280461, -0.37320733,
       -0.53599231, -0.39633002, -0.29978768,  1.60010474,  0.36870656,
        0.62609112, -0.55126849,  1.54012946,  0.17302406,  0.88016974,
        2.31794716,  0.1066234 ,  1.69040229,  0.32099897,  0.34552023,
       -0.28867191,  0.23505897,  0.78538714,  1.61944694,  1.19

In [19]:
import pandas as pd

pac_df = pd.DataFrame(sepal_length_sepal_width_petal_length_petal_width_1 , columns=['sepal_length_sepal_width_petal_length_petal_width_1'])

In [21]:
pac_df['sepal_length_sepal_width_petal_length_petal_width_2'] = sepal_length_sepal_width_petal_length_petal_width_2

In [22]:
pac_df.head()

sepal_length_sepal_width_petal_length_petal_width_1  \
0                                          -0.685250     
1                                           0.220058     
2                                          -0.541303     
3                                          -0.711867     
4                                          -1.126012     

   sepal_length_sepal_width_petal_length_petal_width_2  
0                                          -0.794381    
1                                           0.243538    
2                                          -0.100325    
3                                           0.150840    
4                                          -0.959922